name: y m3u8
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get cn_CCTV4.m3u8
      run: |
        touch ./cn_CCTV4.m3u8
        sudo cat >./cn_CCTV4.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@LiveNow24H/live)
        EOL

    - name: Get cn_CGTN.m3u8
      run: |
        touch ./cn_CGTN.m3u8
        sudo cat >./cn_CGTN.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=Zv60F39Is_c)
        EOL

    - name: Get cn_CGTNFrancais.m3u8
      run: |
        touch ./cn_CGTNFrancais.m3u8
        sudo cat >./cn_CGTNFrancais.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@CGTNFrancais/live)
        EOL

    - name: Get hk_FengHuangZiXun.m3u8
      run: |
        touch ./hk_FengHuangZiXun.m3u8
        sudo cat >./hk_FengHuangZiXun.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@phoenixtvhk/live)
        EOL

    - name: Get ww_ZhongTianXinWen.m3u8
      run: |
        touch ./ww_ZhongTianXinWen.m3u8
        sudo cat >./ww_ZhongTianXinWen.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@CtiTv/live)
        EOL

    - name: Get ww_ZhongTianXinWen2.m3u8
      run: |
        touch ./ww_ZhongTianXinWen2.m3u8
        sudo cat >./ww_ZhongTianXinWen2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@CtiDeepThroat/live)
        EOL

    - name: Get ww_TVBSNews.m3u8
      run: |
        touch ./ww_TVBSNews.m3u8
        sudo cat >./ww_TVBSNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@TVBSNEWS01/live)
        EOL

    - name: Get ww_TVBSNews2.m3u8
      run: |
        touch ./ww_TVBSNews2.m3u8
        sudo cat >./ww_TVBSNews2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@TVBSNEWS02/live)
        EOL

    - name: Get ww_TaiShiXinWen.m3u8
      run: |
        touch ./ww_TaiShiXinWen.m3u8
        sudo cat >./ww_TaiShiXinWen.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@TTV_NEWS/live)
        EOL

    - name: Get ww_ZhongShiXinWen.m3u8
      run: |
        touch ./ww_ZhongShiXinWen.m3u8
        sudo cat >./ww_ZhongShiXinWen.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@twctvnews/live)
        EOL

    - name: Get ww_GongShiXinWen.m3u8
      run: |
        touch ./ww_GongShiXinWen.m3u8
        sudo cat >./ww_GongShiXinWen.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/PNNPTS/live)
        EOL

    - name: Get ww_DongSenXinWen.m3u8
      run: |
        touch ./ww_DongSenXinWen.m3u8
        sudo cat >./ww_DongSenXinWen.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/newsebc/live)
        EOL

    - name: Get ww_DongSenCaiJingXinWen.m3u8
      run: |
        touch ./ww_DongSenCaiJingXinWen.m3u8
        sudo cat >./ww_DongSenCaiJingXinWen.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@57ETFN/live)
        EOL

    - name: Get ww_DongSenCaiJingXinWen2.m3u8
      run: |
        touch ./ww_DongSenCaiJingXinWen2.m3u8
        sudo cat >./ww_DongSenCaiJingXinWen2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=LbS-xQ67fos)
        EOL

    - name: Get ww_MinShiXinWen.m3u8
      run: |
        touch ./ww_MinShiXinWen.m3u8
        sudo cat >./ww_MinShiXinWen.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@FTV_News/live)
        EOL

    - name: Get ww_SanLiiNEWS.m3u8
      run: |
        touch ./ww_SanLiiNEWS.m3u8
        sudo cat >./ww_SanLiiNEWS.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@setinews/live)
        EOL

    - name: Get ww_SanLiiNEWS+.m3u8
      run: |
        touch ./ww_SanLiiNEWS+.m3u8
        sudo cat >./ww_SanLiiNEWS+.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@setnews/live)
        EOL

    - name: Get ww_HuanYuXinWenWW.m3u8
      run: |
        touch ./ww_HuanYuXinWenWW.m3u8
        sudo cat >./ww_HuanYuXinWenWW.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=w87VGpgd90U)
        EOL

    - name: Get ww_HuanYuXinWenQuanQiu.m3u8
      run: |
        touch ./ww_HuanYuXinWenQuanQiu.m3u8
        sudo cat >./ww_HuanYuXinWenQuanQiu.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@globalnewstw/live)
        EOL

    - name: Get ww_HuanYuXinWen24.m3u8
      run: |
        touch ./ww_HuanYuXinWen24.m3u8
        sudo cat >./ww_HuanYuXinWen24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=6IquAgfvYmc)
        EOL

    - name: Get ww_HuanYuXinWenCaiJing.m3u8
      run: |
        touch ./ww_HuanYuXinWenCaiJing.m3u8
        sudo cat >./ww_HuanYuXinWenCaiJing.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@globlemoney/live)
        EOL

    - name: Get ww_JingXinWen.m3u8
      run: |
        touch ./ww_JingXinWen.m3u8
        sudo cat >./ww_JingXinWen.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@mnews-tw/live)
        EOL

    - name: Get ww_YOYOTV.m3u8
      run: |
        touch ./ww_YOYOTV.m3u8
        sudo cat >./ww_YOYOTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@yoyotvebc/live)
        EOL

    - name: Get ww_YunTongCaiJing.m3u8
      run: |
        touch ./ww_YunTongCaiJing.m3u8
        sudo cat >./ww_YunTongCaiJing.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@EFTV01/live)
        EOL

    - name: Get ww_DaAi1.m3u8
      run: |
        touch ./ww_DaAi1.m3u8
        sudo cat >./ww_DaAi1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@DaAiVideo/live)
        EOL

    - name: Get ww_DaAi2.m3u8
      run: |
        touch ./ww_DaAi2.m3u8
        sudo cat >./ww_DaAi2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=DTNkEm6jaqQ)
        EOL

    - name: Get ww_TaiwanPlus.m3u8
      run: |
        touch ./ww_TaiwanPlus.m3u8
        sudo cat >./ww_TaiwanPlus.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@TaiwanPlusLive/live)
        EOL

    - name: Get ww_XinDaTV.m3u8
      run: |
        touch ./ww_XinDaTV.m3u8
        sudo cat >./ww_XinDaTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@user-mj5bl5ze5o/live)
        EOL

    - name: Get ww_HaiTunZongHe.m3u8
      run: |
        touch ./ww_HaiTunZongHe.m3u8
        sudo cat >./ww_HaiTunZongHe.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@24811001/live)
        EOL

    - name: Get ww_NTDAPTV.m3u8
      run: |
        touch ./ww_NTDAPTV.m3u8
        sudo cat >./ww_NTDAPTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/NTDapTV/live)
        EOL

    - name: Get jp_ANNnews.m3u8
      run: |
        touch ./jp_ANNnews.m3u8
        sudo cat >./jp_ANNnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=coYw-eVU0Ks)
        EOL

    - name: Get jp_TBSNewsDIG.m3u8
      run: |
        touch ./jp_TBSNewsDIG.m3u8
        sudo cat >./jp_TBSNewsDIG.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=ohI356mwBp8)
        EOL

    - name: Get jp_HOMENews.m3u8
      run: |
        touch ./jp_HOMENews.m3u8
        sudo cat >./jp_HOMENews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=e2pgLUmaxGs)
        EOL

    - name: Get jp_HTBNews.m3u8
      run: |
        touch ./jp_HTBNews.m3u8
        sudo cat >./jp_HTBNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@htbnews/live)
        EOL

    - name: Get jp_STVNews.m3u8
      run: |
        touch ./jp_STVNews.m3u8
        sudo cat >./jp_STVNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@stv9721/live)
        EOL

    - name: Get jp_KTSKagoshimaNews.m3u8
      run: |
        touch ./jp_KTSKagoshimaNews.m3u8
        sudo cat >./jp_KTSKagoshimaNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@KagoshimaNewsKTS/live)
        EOL

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: y m3u8
        path: .

    - name: Git push assets to "y" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b y
        git add .
        git commit -m "Update y"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin y
