name: y10 m3u8
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get ww_TVBSHD.m3u8
      run: |
        touch ./ww_TVBSHD.m3u8
        sudo cat >./ww_TVBSHD.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=YvdcZ_jpLXE)
        EOL

    - name: Get ww_HuaShiXinWenZiXun.m3u8
      run: |
        touch ./ww_HuaShiXinWenZiXun.m3u8
        sudo cat >./ww_HuaShiXinWenZiXun.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=wM0g8EoUZ_E)
        EOL

    - name: Get ww_DongSenLive.m3u8
      run: |
        touch ./ww_DongSenLive.m3u8
        sudo cat >./ww_DongSenLive.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=E0zhe2gkXBs)
        EOL

    - name: Get ww_SanLiLive.m3u8
      run: |
        touch ./ww_SanLiLive.m3u8
        sudo cat >./ww_SanLiLive.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=FoBfXvlOR6I)
        EOL

    - name: Get kr_YTNNews24.m3u8
      run: |
        touch ./kr_YTNNews24.m3u8
        sudo cat >./kr_YTNNews24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=FJfwehhzIhw)
        EOL

    - name: Get kr_YTNdmb.m3u8
      run: |
        touch ./kr_YTNdmb.m3u8
        sudo cat >./kr_YTNdmb.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@ytndmb/live)
        EOL

    - name: Get kr_KBS_KOREA.m3u8
      run: |
        touch ./kr_KBS_KOREA.m3u8
        sudo cat >./kr_KBS_KOREA.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=OxQQsIvJTTU)
        EOL

    - name: Get fr_EuronewsEnglish.m3u8
      run: |
        touch ./fr_EuronewsEnglish.m3u8
        sudo cat >./fr_EuronewsEnglish.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@euronews/live)
        EOL

    - name: Get fr_franceinfo.m3u8
      run: |
        touch ./fr_franceinfo.m3u8
        sudo cat >./fr_franceinfo.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@franceinfo/live)
        EOL

    - name: Get au_ABCIview.m3u8
      run: |
        touch ./au_ABCIview.m3u8
        sudo cat >./au_ABCIview.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@abcnewsaustralia/live)
        EOL

    - name: Get pk_ARYNews.m3u8
      run: |
        touch ./pk_ARYNews.m3u8
        sudo cat >./pk_ARYNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/ArynewsTvofficial/live)
        EOL

    - name: Get mx_MILENIO.m3u8
      run: |
        touch ./mx_MILENIO.m3u8
        sudo cat >./mx_MILENIO.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@milenio/live)
        EOL

    - name: Get mx_TelediarioMx.m3u8
      run: |
        touch ./mx_TelediarioMx.m3u8
        sudo cat >./mx_TelediarioMx.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@TelediarioMx/live)
        EOL

    - name: Get mx_NMas.m3u8
      run: |
        touch ./mx_NMas.m3u8
        sudo cat >./mx_NMas.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@nmas/live)
        EOL

    - name: Get co_NoticiasCaracol.m3u8
      run: |
        touch ./co_NoticiasCaracol.m3u8
        sudo cat >./co_NoticiasCaracol.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@noticiascaracol/live)
        EOL

    - name: Get co_CityTV.m3u8
      run: |
        touch ./co_CityTV.m3u8
        sudo cat >./co_CityTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@Canalcitytv/live)
        EOL

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: y10 m3u8
        path: .

    - name: Git push assets to "y10" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b y10
        git add .
        git commit -m "Update y10"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin y10
