name: y2 m3u8
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get sg_CNA.m3u8
      run: |
        touch ./sg_CNA.m3u8
        sudo cat >./sg_CNA.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/channelnewsasia/live)
        EOL

    - name: Get jp_NHKWorldJapan.m3u8
      run: |
        touch ./jp_NHKWorldJapan.m3u8
        sudo cat >./jp_NHKWorldJapan.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/NHKWORLDJAPAN/live)
        EOL

    - name: Get jp_ABC6ch.m3u8
      run: |
        touch ./jp_ABC6ch.m3u8
        sudo cat >./jp_ABC6ch.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=iNPUWKft7hA)
        EOL

    - name: Get jp_NagoyaTVnews.m3u8
      run: |
        touch ./jp_NagoyaTVnews.m3u8
        sudo cat >./jp_NagoyaTVnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=-C6FE2m7kX8)
        EOL

    - name: Get jp_HBCNews.m3u8
      run: |
        touch ./jp_HBCNews.m3u8
        sudo cat >./jp_HBCNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@hbc7142/live)
        EOL

    - name: Get kr_Arirang.m3u8
      run: |
        touch ./kr_Arirang.m3u8
        sudo cat >./kr_Arirang.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/Arirang/live)
        EOL

    - name: Get kr_MBC_NEWS.m3u8
      run: |
        touch ./kr_MBC_NEWS.m3u8
        sudo cat >./kr_MBC_NEWS.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/MBCNEWS/live)
        EOL

    - name: Get kr_YTNScience.m3u8
      run: |
        touch ./kr_YTNScience.m3u8
        sudo cat >./kr_YTNScience.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/ytnscience/live)
        EOL

    - name: Get kr_YonhapnewsTV.m3u8
      run: |
        touch ./kr_YonhapnewsTV.m3u8
        sudo cat >./kr_YonhapnewsTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=6QZ_qc75ihU)
        EOL

    - name: Get kr_MaeilEconomicTV.m3u8
      run: |
        touch ./kr_MaeilEconomicTV.m3u8
        sudo cat >./kr_MaeilEconomicTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@MKeconomy_TV/live)
        EOL

    - name: Get kr_WOWTV.m3u8
      run: |
        touch ./kr_WOWTV.m3u8
        sudo cat >./kr_WOWTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/hkwowtv/live)
        EOL

    - name: Get kr_SapiensStudio.m3u8
      run: |
        touch ./kr_SapiensStudio.m3u8
        sudo cat >./kr_SapiensStudio.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@sapiens_studio/live)
        EOL

    - name: Get kr_MTNMoney.m3u8
      run: |
        touch ./kr_MTNMoney.m3u8
        sudo cat >./kr_MTNMoney.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/mtn/live)
        EOL

    - name: Get kr_ChsenTV.m3u8
      run: |
        touch ./kr_ChsenTV.m3u8
        sudo cat >./kr_ChsenTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/chsentv/live)
        EOL

    - name: Get my_AstroAWANI.m3u8
      run: |
        touch ./my_AstroAWANI.m3u8
        sudo cat >./my_AstroAWANI.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/astroawani/live)
        EOL

    - name: Get my_Bernama.m3u8
      run: |
        touch ./my_Bernama.m3u8
        sudo cat >./my_Bernama.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=kebMQM3bDxY)
        EOL

    - name: Get my_BeritaRTM.m3u8
      run: |
        touch ./my_BeritaRTM.m3u8
        sudo cat >./my_BeritaRTM.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/BeritaRTMBES/live)
        EOL

    - name: Get ru_MOCKBA24.m3u8
      run: |
        touch ./ru_MOCKBA24.m3u8
        sudo cat >./ru_MOCKBA24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@LiveMoscow24/live)
        EOL

    - name: Get cl_24HorasTVNChile.m3u8
      run: |
        touch ./cl_24HorasTVNChile.m3u8
        sudo cat >./cl_24HorasTVNChile.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@24Horas_TVNChile/live)
        EOL

    - name: Get cl_tele13.m3u8
      run: |
        touch ./cl_tele13.m3u8
        sudo cat >./cl_tele13.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/tele13/live)
        EOL

    - name: Get cr_MultimediosCostaRica.m3u8
      run: |
        touch ./cr_MultimediosCostaRica.m3u8
        sudo cat >./cr_MultimediosCostaRica.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/MultimediosCostaRica/live)
        EOL

    - name: Get ua_ICTV.m3u8
      run: |
        touch ./ua_ICTV.m3u8
        sudo cat >./ua_ICTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=XiBBbMVGUkQ)
        EOL

    - name: Get ua_1plus1.m3u8
      run: |
        touch ./ua_1plus1.m3u8
        sudo cat >./ua_1plus1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=j5TqaWCCdUg)
        EOL

    - name: Get ua_FreedomLive.m3u8
      run: |
        touch ./ua_FreedomLive.m3u8
        sudo cat >./ua_FreedomLive.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/FREEDOM_LIVE/live)
        EOL

    - name: Get ua_News24.m3u8
      run: |
        touch ./ua_News24.m3u8
        sudo cat >./ua_News24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@news24onlineua/live)
        EOL

    - name: Get ua_pryamiy.m3u8
      run: |
        touch ./ua_pryamiy.m3u8
        sudo cat >./ua_pryamiy.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/pryamiy/live)
        EOL

    - name: Get ua_EspresoTV.m3u8
      run: |
        touch ./ua_EspresoTV.m3u8
        sudo cat >./ua_EspresoTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/EspresoTv/live)
        EOL

    - name: Get ng_ChannelsTelevision1.m3u8
      run: |
        touch ./ng_ChannelsTelevision1.m3u8
        sudo cat >./ng_ChannelsTelevision1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=dfB0qmJo1eM)
        EOL

    - name: Get ng_ChannelsTelevision2.m3u8
      run: |
        touch ./ng_ChannelsTelevision2.m3u8
        sudo cat >./ng_ChannelsTelevision2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/ChannelsTelevision/live)
        EOL

    - name: Get ng_MFMTelevision.m3u8
      run: |
        touch ./ng_MFMTelevision.m3u8
        sudo cat >./ng_MFMTelevision.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/MFMTelevision/live)
        EOL

    - name: Get dz_AlmagharibiaTV.m3u8
      run: |
        touch ./dz_AlmagharibiaTV.m3u8
        sudo cat >./dz_AlmagharibiaTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/AlmagharibiaTv/live)
        EOL

    - name: Get ug_NTVUganda.m3u8
      run: |
        touch ./ug_NTVUganda.m3u8
        sudo cat >./ug_NTVUganda.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/ntvuganda/live)
        EOL

    - name: Get un_UnitedNations.m3u8
      run: |
        touch ./un_UnitedNations.m3u8
        sudo cat >./un_UnitedNations.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/unitednations/live)
        EOL

    - name: Get in_News18India.m3u8
      run: |
        touch ./in_News18India.m3u8
        sudo cat >./in_News18India.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=HBorWH77wPs)
        EOL

    - name: Get in_News18MPChhattisgarh.m3u8
      run: |
        touch ./in_News18MPChhattisgarh.m3u8
        sudo cat >./in_News18MPChhattisgarh.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=ivh1DmEWI88)
        EOL

    - name: Get in_News18Rajasthan.m3u8
      run: |
        touch ./in_News18Rajasthan.m3u8
        sudo cat >./in_News18Rajasthan.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=IbWK8xuVQgs)
        EOL

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: y2 m3u8
        path: .

    - name: Git push assets to "y2" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b y2
        git add .
        git commit -m "Update y2"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin y2
