name: y3 m3u8
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get us_CNBC.m3u8
      run: |
        touch ./us_CNBC.m3u8
        sudo cat >./us_CNBC.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/CNBC/live)
        EOL

    - name: Get us_CNBCArabia.m3u8
      run: |
        touch ./us_CNBCArabia.m3u8
        sudo cat >./us_CNBCArabia.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/cnbcarabiaTV/live)
        EOL

    - name: Get us_NBCNews.m3u8
      run: |
        touch ./us_NBCNews.m3u8
        sudo cat >./us_NBCNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/NBCNews/live)
        EOL

    - name: Get us_NBC2News.m3u8
      run: |
        touch ./us_NBC2News.m3u8
        sudo cat >./us_NBC2News.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/NBC2swfl/live)
        EOL

    - name: Get us_FoxNewsNow.m3u8
      run: |
        touch ./us_FoxNewsNow.m3u8
        sudo cat >./us_FoxNewsNow.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=3_-jZqsQqdk)
        EOL

    - name: Get us_FoxNewsNow2.m3u8
      run: |
        touch ./us_FoxNewsNow2.m3u8
        sudo cat >./us_FoxNewsNow2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/livenowfox/live)
        EOL

    - name: Get us_FOXWeather.m3u8
      run: |
        touch ./us_FOXWeather.m3u8
        sudo cat >./us_FOXWeather.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/Foxweather/live)
        EOL

    - name: Get us_ABCNews.m3u8
      run: |
        touch ./us_ABCNews.m3u8
        sudo cat >./us_ABCNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=OOtxXPaQvoM)
        EOL

    - name: Get us_ABCNews2.m3u8
      run: |
        touch ./us_ABCNews2.m3u8
        sudo cat >./us_ABCNews2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/ABCNews/live)
        EOL

    - name: Get us_ABC7NewsSWFL.m3u8
      run: |
        touch ./us_ABC7NewsSWFL.m3u8
        sudo cat >./us_ABC7NewsSWFL.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=eXZ4-qp16nI)
        EOL

    - name: Get us_ABC7EyewitnessNews.m3u8
      run: |
        touch ./us_ABC7EyewitnessNews.m3u8
        sudo cat >./us_ABC7EyewitnessNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/ABC7/live)
        EOL

    - name: Get us_WPBF25News.m3u8
      run: |
        touch ./us_WPBF25News.m3u8
        sudo cat >./us_WPBF25News.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/WPBF/live)
        EOL

    - name: Get us_WPLGLocal10.m3u8
      run: |
        touch ./us_WPLGLocal10.m3u8
        sudo cat >./us_WPLGLocal10.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/WPLGLocal10/live)
        EOL

    - name: Get us_BloombergBusinessNews.m3u8
      run: |
        touch ./us_BloombergBusinessNews.m3u8
        sudo cat >./us_BloombergBusinessNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=iyOq8DhaMYw)
        EOL

    - name: Get us_BloombergOriginals.m3u8
      run: |
        touch ./us_BloombergOriginals.m3u8
        sudo cat >./us_BloombergOriginals.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=DxmDPrfinXY)
        EOL

    - name: Get us_NatGeoWILD.m3u8
      run: |
        touch ./us_NatGeoWILD.m3u8
        sudo cat >./us_NatGeoWILD.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=BJ3Yv572V1A)
        EOL

    - name: Get us_NatGeoWILD2.m3u8
      run: |
        touch ./us_NatGeoWILD2.m3u8
        sudo cat >./us_NatGeoWILD2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/NatGeoWild/live)
        EOL

    - name: Get us_SonLifeBroadcastingNetwork.m3u8
      run: |
        touch ./us_SonLifeBroadcastingNetwork.m3u8
        sudo cat >./us_SonLifeBroadcastingNetwork.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/SonlifeTV/live)
        EOL

    - name: Get us_YahooFinance.m3u8
      run: |
        touch ./us_YahooFinance.m3u8
        sudo cat >./us_YahooFinance.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/YahooFinance/live)
        EOL

    - name: Get us_SchwabNetwork.m3u8
      run: |
        touch ./us_SchwabNetwork.m3u8
        sudo cat >./us_SchwabNetwork.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=BWhVz1ozr1o)
        EOL

    - name: Get us_WCVBChannel5Boston.m3u8
      run: |
        touch ./us_WCVBChannel5Boston.m3u8
        sudo cat >./us_WCVBChannel5Boston.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/WCVB/live)
        EOL

    - name: Get us_4029News.m3u8
      run: |
        touch ./us_4029News.m3u8
        sudo cat >./us_4029News.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/4029news/live)
        EOL

    - name: Get us_News12NewYork.m3u8
      run: |
        touch ./us_News12NewYork.m3u8
        sudo cat >./us_News12NewYork.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/news12/live)
        EOL

    - name: Get us_WRAL.m3u8
      run: |
        touch ./us_WRAL.m3u8
        sudo cat >./us_WRAL.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/WRAL5/live)
        EOL

    - name: Get us_KCRA3.m3u8
      run: |
        touch ./us_KCRA3.m3u8
        sudo cat >./us_KCRA3.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/KCRA/live)
        EOL

    - name: Get us_WESH2News.m3u8
      run: |
        touch ./us_WESH2News.m3u8
        sudo cat >./us_WESH2News.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/WESH/live)
        EOL

    - name: Get us_WMURTV.m3u8
      run: |
        touch ./us_WMURTV.m3u8
        sudo cat >./us_WMURTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/WMUR/live)
        EOL

    - name: Get us_WMTWTV.m3u8
      run: |
        touch ./us_WMTWTV.m3u8
        sudo cat >./us_WMTWTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/WMTWTV/live)
        EOL

    - name: Get us_KOCO5News.m3u8
      run: |
        touch ./us_KOCO5News.m3u8
        sudo cat >./us_KOCO5News.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/KOCO/live)
        EOL

    - name: Get us_USATODAY.m3u8
      run: |
        touch ./us_USATODAY.m3u8
        sudo cat >./us_USATODAY.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/USATODAY/live)
        EOL

    - name: Get us_CBNNews.m3u8
      run: |
        touch ./us_CBNNews.m3u8
        sudo cat >./us_CBNNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/CBNnewsonline/live)
        EOL

    - name: Get us_WVTM13News.m3u8
      run: |
        touch ./us_WVTM13News.m3u8
        sudo cat >./us_WVTM13News.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/WVTM13News/live)
        EOL

    - name: Get us_KSBWActionNews8.m3u8
      run: |
        touch ./us_KSBWActionNews8.m3u8
        sudo cat >./us_KSBWActionNews8.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/KSBW/live)
        EOL

    - name: Get us_CurrentTimeTV.m3u8
      run: |
        touch ./us_CurrentTimeTV.m3u8
        sudo cat >./us_CurrentTimeTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/CurrentTimeTV/live)
        EOL

    - name: Get us_16WAPTNews.m3u8
      run: |
        touch ./us_16WAPTNews.m3u8
        sudo cat >./us_16WAPTNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/16WAPTNews/live)
        EOL

    - name: Get us_AlHurra.m3u8
      run: |
        touch ./us_AlHurra.m3u8
        sudo cat >./us_AlHurra.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/alhurra/live)
        EOL

    - name: Get uk_GBNews.m3u8
      run: |
        touch ./uk_GBNews.m3u8
        sudo cat >./uk_GBNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/GBNewsOnline/live)
        EOL

    - name: Get uk_BBCNewsArabic.m3u8
      run: |
        touch ./uk_BBCNewsArabic.m3u8
        sudo cat >./uk_BBCNewsArabic.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/bbcarabic/live)
        EOL

    - name: Get uk_BBCNewsPersian.m3u8
      run: |
        touch ./uk_BBCNewsPersian.m3u8
        sudo cat >./uk_BBCNewsPersian.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/BBCPersian/live)
        EOL

    - name: Get uk_TalkTV.m3u8
      run: |
        touch ./uk_TalkTV.m3u8
        sudo cat >./uk_TalkTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=WguRyzIb4bE)
        EOL

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: y3 m3u8
        path: .

    - name: Git push assets to "y3" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b y3
        git add .
        git commit -m "Update y3"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin y3
