name: y4 m3u8
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get fr_FRANCE24English.m3u8
      run: |
        touch ./fr_FRANCE24English.m3u8
        sudo cat >./fr_FRANCE24English.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/FRANCE24English/live)
        EOL

    - name: Get fr_FRANCE24France.m3u8
      run: |
        touch ./fr_FRANCE24France.m3u8
        sudo cat >./fr_FRANCE24France.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/FRANCE24/live)
        EOL

    - name: Get fr_FRANCE24Espanol.m3u8
      run: |
        touch ./fr_FRANCE24Espanol.m3u8
        sudo cat >./fr_FRANCE24Espanol.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/FRANCE24Espanol/live)
        EOL

    - name: Get fr_FRANCE24Arabic.m3u8
      run: |
        touch ./fr_FRANCE24Arabic.m3u8
        sudo cat >./fr_FRANCE24Arabic.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/FRANCE24Arabic/live)
        EOL

    - name: Get fr_EuronewsFrance.m3u8
      run: |
        touch ./fr_EuronewsFrance.m3u8
        sudo cat >./fr_EuronewsFrance.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/euronewsfr/live)
        EOL

    - name: Get fr_EuronewsEspanol.m3u8
      run: |
        touch ./fr_EuronewsEspanol.m3u8
        sudo cat >./fr_EuronewsEspanol.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/euronewses/live)
        EOL

    - name: Get fr_EuronewsRussian.m3u8
      run: |
        touch ./fr_EuronewsRussian.m3u8
        sudo cat >./fr_EuronewsRussian.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/euronewsru/live)
        EOL

    - name: Get fr_EuronewsDeutsch.m3u8
      run: |
        touch ./fr_EuronewsDeutsch.m3u8
        sudo cat >./fr_EuronewsDeutsch.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/euronewsde/live)
        EOL

    - name: Get fr_EuronewsItaliano.m3u8
      run: |
        touch ./fr_EuronewsItaliano.m3u8
        sudo cat >./fr_EuronewsItaliano.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/euronewsit/live)
        EOL

    - name: Get fr_EuronewsPortuguesa.m3u8
      run: |
        touch ./fr_EuronewsPortuguesa.m3u8
        sudo cat >./fr_EuronewsPortuguesa.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/euronewspt/live)
        EOL

    - name: Get fr_EuronewsGreek.m3u8
      run: |
        touch ./fr_EuronewsGreek.m3u8
        sudo cat >./fr_EuronewsGreek.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/euronews_greek/live)
        EOL

    - name: Get fr_EuronewsRomania.m3u8
      run: |
        touch ./fr_EuronewsRomania.m3u8
        sudo cat >./fr_EuronewsRomania.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/euronewsro/live)
        EOL

    - name: Get fr_EuronewsMagyarul.m3u8
      run: |
        touch ./fr_EuronewsMagyarul.m3u8
        sudo cat >./fr_EuronewsMagyarul.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@euronewshu/live)
        EOL

    - name: Get fr_EuronewsAlbania.m3u8
      run: |
        touch ./fr_EuronewsAlbania.m3u8
        sudo cat >./fr_EuronewsAlbania.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/EuronewsAlbania/live)
        EOL

    - name: Get fr_AfricanewsEnglish.m3u8
      run: |
        touch ./fr_AfricanewsEnglish.m3u8
        sudo cat >./fr_AfricanewsEnglish.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/africanews/live)
        EOL

    - name: Get fr_AfricanewsFrance.m3u8
      run: |
        touch ./fr_AfricanewsFrance.m3u8
        sudo cat >./fr_AfricanewsFrance.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/africanewsfr/live)
        EOL

    - name: Get fr_LeMedia.m3u8
      run: |
        touch ./fr_LeMedia.m3u8
        sudo cat >./fr_LeMedia.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/LeMediaOfficiel/live)
        EOL

    - name: Get de_DWNews.m3u8
      run: |
        touch ./de_DWNews.m3u8
        sudo cat >./de_DWNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/dwnews/live)
        EOL

    - name: Get de_DWDeutsch.m3u8
      run: |
        touch ./de_DWDeutsch.m3u8
        sudo cat >./de_DWDeutsch.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/dwdeutsch/live)
        EOL

    - name: Get de_DWNewsEspanol.m3u8
      run: |
        touch ./de_DWNewsEspanol.m3u8
        sudo cat >./de_DWNewsEspanol.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/dwespanol/live)
        EOL

    - name: Get de_DWNewsArabic.m3u8
      run: |
        touch ./de_DWNewsArabic.m3u8
        sudo cat >./de_DWNewsArabic.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/dwarabic/live)
        EOL

    - name: Get de_earthTV1.m3u8
      run: |
        touch ./de_earthTV1.m3u8
        sudo cat >./de_earthTV1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=HfgIFGbdGJ0)
        EOL

    - name: Get de_earthTV2.m3u8
      run: |
        touch ./de_earthTV2.m3u8
        sudo cat >./de_earthTV2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/earthTV/live)
        EOL

    - name: Get es_RTVENoticias.m3u8
      run: |
        touch ./es_RTVENoticias.m3u8
        sudo cat >./es_RTVENoticias.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/rtvenoticias/live)
        EOL

    - name: Get es_Malaga24h.m3u8
      run: |
        touch ./es_Malaga24h.m3u8
        sudo cat >./es_Malaga24h.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/Malaga24h/live)
        EOL

    - name: Get es_TelevisionCanaria.m3u8
      run: |
        touch ./es_TelevisionCanaria.m3u8
        sudo cat >./es_TelevisionCanaria.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/TelevisionCanaria/live)
        EOL

    - name: Get es_canalsur.m3u8
      run: |
        touch ./es_canalsur.m3u8
        sudo cat >./es_canalsur.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/canalsur/live)
        EOL

    - name: Get es_TelevisiondeGalicia.m3u8
      run: |
        touch ./es_TelevisiondeGalicia.m3u8
        sudo cat >./es_TelevisiondeGalicia.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=35oTS5zl2rM)
        EOL

    - name: Get es_ETBBasque.m3u8
      run: |
        touch ./es_ETBBasque.m3u8
        sudo cat >./es_ETBBasque.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/EitbEus/live)
        EOL

    - name: Get it_Skytg24.m3u8
      run: |
        touch ./it_Skytg24.m3u8
        sudo cat >./it_Skytg24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@skytg24/live)
        EOL

    - name: Get be_MedyaHaberTV.m3u8
      run: |
        touch ./be_MedyaHaberTV.m3u8
        sudo cat >./be_MedyaHaberTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/MedyaHaberTV1/live)
        EOL

    - name: Get at_OE24TV.m3u8
      run: |
        touch ./at_OE24TV.m3u8
        sudo cat >./at_OE24TV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/oe24TV/live)
        EOL

    - name: Get qa_AlJazeera.m3u8
      run: |
        touch ./qa_AlJazeera.m3u8
        sudo cat >./qa_AlJazeera.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/aljazeeraenglish/live)
        EOL

    - name: Get qa_AlJazeeraMubasher.m3u8
      run: |
        touch ./qa_AlJazeeraMubasher.m3u8
        sudo cat >./qa_AlJazeeraMubasher.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=eksOMqVMINo)
        EOL

    - name: Get qa_AlJazeeraArabic.m3u8
      run: |
        touch ./qa_AlJazeeraArabic.m3u8
        sudo cat >./qa_AlJazeeraArabic.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/aljazeera/live)
        EOL

    - name: Get qa_AlJazeeraBalkans.m3u8
      run: |
        touch ./qa_AlJazeeraBalkans.m3u8
        sudo cat >./qa_AlJazeeraBalkans.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/ajbalkans/live)
        EOL

    - name: Get qa_Alaraby.m3u8
      run: |
        touch ./qa_Alaraby.m3u8
        sudo cat >./qa_Alaraby.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/AlarabyTv_News/live)
        EOL

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: y4 m3u8
        path: .

    - name: Git push assets to "y4" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b y4
        git add .
        git commit -m "Update y4"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin y4
