name: y7 m3u8
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get in_KalaignarTVNews.m3u8
      run: |
        touch ./in_KalaignarTVNews.m3u8
        sudo cat >./in_KalaignarTVNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@KalaignarTVNews/live)
        EOL

    - name: Get in_SaamTV.m3u8
      run: |
        touch ./in_SaamTV.m3u8
        sudo cat >./in_SaamTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@SaamTV/live)
        EOL

    - name: Get in_NewsJ.m3u8
      run: |
        touch ./in_NewsJ.m3u8
        sudo cat >./in_NewsJ.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/newsj/live)
        EOL

    - name: Get in_SathiyamNews.m3u8
      run: |
        touch ./in_SathiyamNews.m3u8
        sudo cat >./in_SathiyamNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/SathiyamTV/live)
        EOL

    - name: Get in_ShekinahNews.m3u8
      run: |
        touch ./in_ShekinahNews.m3u8
        sudo cat >./in_ShekinahNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@globalshekinah/live)
        EOL

    - name: Get in_ABPAsmita.m3u8
      run: |
        touch ./in_ABPAsmita.m3u8
        sudo cat >./in_ABPAsmita.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@ABPAsmitaTV/live)
        EOL

    - name: Get in_OTVEnglish.m3u8
      run: |
        touch ./in_OTVEnglish.m3u8
        sudo cat >./in_OTVEnglish.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@otvodisha/live)
        EOL

    - name: Get in_SwatantraTV.m3u8
      run: |
        touch ./in_SwatantraTV.m3u8
        sudo cat >./in_SwatantraTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@swatantralive/live)
        EOL

    - name: Get in_DDKashir.m3u8
      run: |
        touch ./in_DDKashir.m3u8
        sudo cat >./in_DDKashir.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@DDKashirchannel/live)
        EOL

    - name: Get in_RTVNewsTelugu.m3u8
      run: |
        touch ./in_RTVNewsTelugu.m3u8
        sudo cat >./in_RTVNewsTelugu.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@RTVNewsNetwork/live)
        EOL

    - name: Get in_PTCNews.m3u8
      run: |
        touch ./in_PTCNews.m3u8
        sudo cat >./in_PTCNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@ptcnews/live)
        EOL

    - name: Get in_KanakNews.m3u8
      run: |
        touch ./in_KanakNews.m3u8
        sudo cat >./in_KanakNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@KanakNewsOdisha/live)
        EOL

    - name: Get in_NEWS9.m3u8
      run: |
        touch ./in_NEWS9.m3u8
        sudo cat >./in_NEWS9.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@NEWS9LIVE/live)
        EOL

    - name: Get in_HarvestTV.m3u8
      run: |
        touch ./in_HarvestTV.m3u8
        sudo cat >./in_HarvestTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@harvesttv7644/live)
        EOL

    - name: Get in_NandighoshaTV.m3u8
      run: |
        touch ./in_NandighoshaTV.m3u8
        sudo cat >./in_NandighoshaTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/NandighoshaTV/live)
        EOL

    - name: Get in_Bharat24.m3u8
      run: |
        touch ./in_Bharat24.m3u8
        sudo cat >./in_Bharat24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@Bharat24Liv/live)
        EOL

    - name: Get in_JaiMaharashtraNews.m3u8
      run: |
        touch ./in_JaiMaharashtraNews.m3u8
        sudo cat >./in_JaiMaharashtraNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/jaimaharashtranews/live)
        EOL

    - name: Get in_KeralaVisionNews.m3u8
      run: |
        touch ./in_KeralaVisionNews.m3u8
        sudo cat >./in_KeralaVisionNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@keralavisionnews24x7/live)
        EOL

    - name: Get bd_Channel24.m3u8
      run: |
        touch ./bd_Channel24.m3u8
        sudo cat >./bd_Channel24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@channel24digital/live)
        EOL

    - name: Get bd_ChanneliNews.m3u8
      run: |
        touch ./bd_ChanneliNews.m3u8
        sudo cat >./bd_ChanneliNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/channelinews/live)
        EOL

    - name: Get bd_RtvNews.m3u8
      run: |
        touch ./bd_RtvNews.m3u8
        sudo cat >./bd_RtvNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@RtvNews/live)
        EOL

    - name: Get bd_EKHONTV.m3u8
      run: |
        touch ./bd_EKHONTV.m3u8
        sudo cat >./bd_EKHONTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@ekhontv/live)
        EOL

    - name: Get bd_EkattorTV.m3u8
      run: |
        touch ./bd_EkattorTV.m3u8
        sudo cat >./bd_EkattorTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@EkattorTelevision/live)
        EOL

    - name: Get bd_IndependentTelevision.m3u8
      run: |
        touch ./bd_IndependentTelevision.m3u8
        sudo cat >./bd_IndependentTelevision.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@IndependentTelevision/live)
        EOL

    - name: Get ph_DZRHNews.m3u8
      run: |
        touch ./ph_DZRHNews.m3u8
        sudo cat >./ph_DZRHNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@DZRHTV/live)
        EOL

    - name: Get ph_UNTVNewsandRescue.m3u8
      run: |
        touch ./ph_UNTVNewsandRescue.m3u8
        sudo cat >./ph_UNTVNewsandRescue.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@UNTVNewsandRescue/live)
        EOL

    - name: Get ph_ABSCBNEntertainment.m3u8
      run: |
        touch ./ph_ABSCBNEntertainment.m3u8
        sudo cat >./ph_ABSCBNEntertainment.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/abscbnentertainment/live)
        EOL

    - name: Get id_tvOneNews.m3u8
      run: |
        touch ./id_tvOneNews.m3u8
        sudo cat >./id_tvOneNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@tvOneNews/live)
        EOL

    - name: Get id_KOMPASTV.m3u8
      run: |
        touch ./id_KOMPASTV.m3u8
        sudo cat >./id_KOMPASTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/kompastv/live)
        EOL

    - name: Get id_KompasTVMedan.m3u8
      run: |
        touch ./id_KompasTVMedan.m3u8
        sudo cat >./id_KompasTVMedan.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@kompastvmedan/live)
        EOL

    - name: Get id_Liputan6.m3u8
      run: |
        touch ./id_Liputan6.m3u8
        sudo cat >./id_Liputan6.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@liputan6_news/live)
        EOL

    - name: Get id_METROTV.m3u8
      run: |
        touch ./id_METROTV.m3u8
        sudo cat >./id_METROTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@metrotvnews/live)
        EOL

    - name: Get id_Tribunnews.m3u8
      run: |
        touch ./id_Tribunnews.m3u8
        sudo cat >./id_Tribunnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/tribunnews/live)
        EOL

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: y7 m3u8
        path: .

    - name: Git push assets to "y7" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b y7
        git add .
        git commit -m "Update y7"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin y7
