name: y8 m3u8
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get in_BIGTVTeluguNews.m3u8
      run: |
        touch ./in_BIGTVTeluguNews.m3u8
        sudo cat >./in_BIGTVTeluguNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=ueJsgNKeq8c)
        EOL

    - name: Get in_24NewsMalayalam.m3u8
      run: |
        touch ./in_24NewsMalayalam.m3u8
        sudo cat >./in_24NewsMalayalam.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/24OnLive/live)
        EOL

    - name: Get in_AsianetNews.m3u8
      run: |
        touch ./in_AsianetNews.m3u8
        sudo cat >./in_AsianetNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/asianetnews/live)
        EOL

    - name: Get in_ZoomOnNews.m3u8
      run: |
        touch ./in_ZoomOnNews.m3u8
        sudo cat >./in_ZoomOnNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/zoomonnews/live)
        EOL

    - name: Get pk_GeoNews.m3u8
      run: |
        touch ./pk_GeoNews.m3u8
        sudo cat >./pk_GeoNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/geonews/live)
        EOL

    - name: Get pk_HUMNews.m3u8
      run: |
        touch ./pk_HUMNews.m3u8
        sudo cat >./pk_HUMNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/HUMNewsPakistan/live)
        EOL

    - name: Get pk_24NewsHD.m3u8
      run: |
        touch ./pk_24NewsHD.m3u8
        sudo cat >./pk_24NewsHD.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/24NewsHD/live)
        EOL

    - name: Get pk_SAMAANews.m3u8
      run: |
        touch ./pk_SAMAANews.m3u8
        sudo cat >./pk_SAMAANews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/samaatvnews/live)
        EOL

    - name: Get pk_City21News.m3u8
      run: |
        touch ./pk_City21News.m3u8
        sudo cat >./pk_City21News.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=DRrIqa0C1z0)
        EOL

    - name: Get pk_City42News.m3u8
      run: |
        touch ./pk_City42News.m3u8
        sudo cat >./pk_City42News.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/City42Lahore/live)
        EOL

    - name: Get pk_BOLNews.m3u8
      run: |
        touch ./pk_BOLNews.m3u8
        sudo cat >./pk_BOLNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=LrgH83Fxo58)
        EOL

    - name: Get pk_BOLNews2.m3u8
      run: |
        touch ./pk_BOLNews2.m3u8
        sudo cat >./pk_BOLNews2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/BOLNewsofficial/live)
        EOL

    - name: Get pk_ARYQtv.m3u8
      run: |
        touch ./pk_ARYQtv.m3u8
        sudo cat >./pk_ARYQtv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/ARYQtvofficial/live)
        EOL

    - name: Get pk_AajNews.m3u8
      run: |
        touch ./pk_AajNews.m3u8
        sudo cat >./pk_AajNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/AajTVofficial/live)
        EOL

    - name: Get pk_DawnNews.m3u8
      run: |
        touch ./pk_DawnNews.m3u8
        sudo cat >./pk_DawnNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/dawnnewspakistan/live)
        EOL

    - name: Get pk_GTVNetworkHD.m3u8
      run: |
        touch ./pk_GTVNetworkHD.m3u8
        sudo cat >./pk_GTVNetworkHD.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/GTVNetworkHD/live)
        EOL

    - name: Get pk_PTVNews.m3u8
      run: |
        touch ./pk_PTVNews.m3u8
        sudo cat >./pk_PTVNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/PTVNewsOfficial/live)
        EOL

    - name: Get pk_PTVWorld.m3u8
      run: |
        touch ./pk_PTVWorld.m3u8
        sudo cat >./pk_PTVWorld.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/PTVWorldOfficial/live)
        EOL

    - name: Get pk_PTVHomeEntertainment.m3u8
      run: |
        touch ./pk_PTVHomeEntertainment.m3u8
        sudo cat >./pk_PTVHomeEntertainment.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/PTVHomeEntertainment/live)
        EOL

    - name: Get pk_ExpressNews.m3u8
      run: |
        touch ./pk_ExpressNews.m3u8
        sudo cat >./pk_ExpressNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=z3gT8L18mgM)
        EOL

    - name: Get pk_GNNNews.m3u8
      run: |
        touch ./pk_GNNNews.m3u8
        sudo cat >./pk_GNNNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/gnnhdofficial/live)
        EOL

    - name: Get np_News24Nepal.m3u8
      run: |
        touch ./np_News24Nepal.m3u8
        sudo cat >./np_News24Nepal.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/news24tvchannel/live)
        EOL

    - name: Get sa_AlArabiya.m3u8
      run: |
        touch ./sa_AlArabiya.m3u8
        sudo cat >./sa_AlArabiya.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/AlArabiya/live)
        EOL

    - name: Get sa_AlHadath.m3u8
      run: |
        touch ./sa_AlHadath.m3u8
        sudo cat >./sa_AlHadath.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/AlHadath/live)
        EOL

    - name: Get sa_AsharqNews.m3u8
      run: |
        touch ./sa_AsharqNews.m3u8
        sudo cat >./sa_AsharqNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/AsharqNews/live)
        EOL

    - name: Get sa_AsharqBusiness.m3u8
      run: |
        touch ./sa_AsharqBusiness.m3u8
        sudo cat >./sa_AsharqBusiness.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=MYIqDdUwlsg)
        EOL

    - name: Get sa_Alekhbariya.m3u8
      run: |
        touch ./sa_Alekhbariya.m3u8
        sudo cat >./sa_Alekhbariya.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/SaudiNewsTV/live)
        EOL

    - name: Get ye_BelqeesTV.m3u8
      run: |
        touch ./ye_BelqeesTV.m3u8
        sudo cat >./ye_BelqeesTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/BelqeesTV/live)
        EOL

    - name: Get lb_AlMayadeen.m3u8
      run: |
        touch ./lb_AlMayadeen.m3u8
        sudo cat >./lb_AlMayadeen.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/AlMayadeenLive1/live)
        EOL

    - name: Get eg_alkaherawalnas.m3u8
      run: |
        touch ./eg_alkaherawalnas.m3u8
        sudo cat >./eg_alkaherawalnas.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=beW5BF_vfKw)
        EOL

    - name: Get eg_alkaherawalnas2.m3u8
      run: |
        touch ./eg_alkaherawalnas2.m3u8
        sudo cat >./eg_alkaherawalnas2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=EMcvfLUKo6U)
        EOL

    - name: Get eg_AlghadExtra.m3u8
      run: |
        touch ./eg_AlghadExtra.m3u8
        sudo cat >./eg_AlghadExtra.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/AlghadExtra/live)
        EOL

    - name: Get iq_KarbalaTV.m3u8
      run: |
        touch ./iq_KarbalaTV.m3u8
        sudo cat >./iq_KarbalaTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/KarbalatvGroup/live)
        EOL

    - name: Get iq_JinTVZindi.m3u8
      run: |
        touch ./iq_JinTVZindi.m3u8
        sudo cat >./iq_JinTVZindi.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=TuxJwMEIhlU)
        EOL

    - name: Get ke_CitizenTV.m3u8
      run: |
        touch ./ke_CitizenTV.m3u8
        sudo cat >./ke_CitizenTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/kenyacitizentv/live)
        EOL

    - name: Get ke_NTVKenya.m3u8
      run: |
        touch ./ke_NTVKenya.m3u8
        sudo cat >./ke_NTVKenya.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/ntvkenyaonline/live)
        EOL

    - name: Get ke_KTNNewsKenya.m3u8
      run: |
        touch ./ke_KTNNewsKenya.m3u8
        sudo cat >./ke_KTNNewsKenya.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/standardgroupkenya/live)
        EOL

    - name: Get mx_adn40Mx.m3u8
      run: |
        touch ./mx_adn40Mx.m3u8
        sudo cat >./mx_adn40Mx.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/c/ADN40MX/live)
        EOL

    - name: Get mx_TelevisaPuebla.m3u8
      run: |
        touch ./mx_TelevisaPuebla.m3u8
        sudo cat >./mx_TelevisaPuebla.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/televisapuebla/live)
        EOL

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: y8 m3u8
        path: .

    - name: Git push assets to "y8" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b y8
        git add .
        git commit -m "Update y8"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin y8
