name: y8 m3u8
on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get in_BIGTVTeluguNews.m3u8
      run: |
        touch ./in_BIGTVTeluguNews.m3u8
        sudo cat >./in_BIGTVTeluguNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/watch?v=ueJsgNKeq8c)
        EOL

    - name: Get in_24NewsMalayalam.m3u8
      run: |
        touch ./in_24NewsMalayalam.m3u8
        sudo cat >./in_24NewsMalayalam.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@24OnLive/live)
        EOL

    - name: Get in_AsianetNews.m3u8
      run: |
        touch ./in_AsianetNews.m3u8
        sudo cat >./in_AsianetNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@asianetnews/live)
        EOL

    - name: Get pk_GeoNews.m3u8
      run: |
        touch ./pk_GeoNews.m3u8
        sudo cat >./pk_GeoNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@geonews/live)
        EOL

    - name: Get pk_HUMNews.m3u8
      run: |
        touch ./pk_HUMNews.m3u8
        sudo cat >./pk_HUMNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@HUMNewsPakistan/live)
        EOL

    - name: Get pk_24NewsHD.m3u8
      run: |
        touch ./pk_24NewsHD.m3u8
        sudo cat >./pk_24NewsHD.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@24NewsHD/live)
        EOL

    - name: Get pk_SAMAANews.m3u8
      run: |
        touch ./pk_SAMAANews.m3u8
        sudo cat >./pk_SAMAANews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/samaatvnews/live)
        EOL

    - name: Get pk_City21News.m3u8
      run: |
        touch ./pk_City21News.m3u8
        sudo cat >./pk_City21News.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@City21/live)
        EOL

    - name: Get pk_City42News.m3u8
      run: |
        touch ./pk_City42News.m3u8
        sudo cat >./pk_City42News.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@City42Lahore/live)
        EOL

    - name: Get pk_BOLNews.m3u8
      run: |
        touch ./pk_BOLNews.m3u8
        sudo cat >./pk_BOLNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@BOLNewsofficial/live)
        EOL

    - name: Get pk_ARYQtv.m3u8
      run: |
        touch ./pk_ARYQtv.m3u8
        sudo cat >./pk_ARYQtv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@ARYQtvofficial/live)
        EOL

    - name: Get pk_AajNews.m3u8
      run: |
        touch ./pk_AajNews.m3u8
        sudo cat >./pk_AajNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@AajTVofficial/live)
        EOL

    - name: Get pk_DawnNews.m3u8
      run: |
        touch ./pk_DawnNews.m3u8
        sudo cat >./pk_DawnNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@dawnnewspakistan/live)
        EOL

    - name: Get pk_GTVNetworkHD.m3u8
      run: |
        touch ./pk_GTVNetworkHD.m3u8
        sudo cat >./pk_GTVNetworkHD.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/gtvnetworkhd/live)
        EOL

    - name: Get pk_PTVNews.m3u8
      run: |
        touch ./pk_PTVNews.m3u8
        sudo cat >./pk_PTVNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@PTVNewsOfficial/live)
        EOL

    - name: Get pk_PTVWorld.m3u8
      run: |
        touch ./pk_PTVWorld.m3u8
        sudo cat >./pk_PTVWorld.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@PTVWorldOfficial/live)
        EOL

    - name: Get pk_PTVHomeEntertainment.m3u8
      run: |
        touch ./pk_PTVHomeEntertainment.m3u8
        sudo cat >./pk_PTVHomeEntertainment.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@PTVHomeEntertainment/live)
        EOL

    - name: Get pk_ExpressNews.m3u8
      run: |
        touch ./pk_ExpressNews.m3u8
        sudo cat >./pk_ExpressNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@ExpressNewspkofficial/live)
        EOL

    - name: Get pk_GNNNews.m3u8
      run: |
        touch ./pk_GNNNews.m3u8
        sudo cat >./pk_GNNNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@gnnhdofficial/live)
        EOL

    - name: Get np_News24Nepal.m3u8
      run: |
        touch ./np_News24Nepal.m3u8
        sudo cat >./np_News24Nepal.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@news24tvchannel/live)
        EOL

    - name: Get sa_AlArabiya.m3u8
      run: |
        touch ./sa_AlArabiya.m3u8
        sudo cat >./sa_AlArabiya.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/AlArabiya/live)
        EOL

    - name: Get sa_AlHadath.m3u8
      run: |
        touch ./sa_AlHadath.m3u8
        sudo cat >./sa_AlHadath.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@AlHadath/live)
        EOL

    - name: Get sa_AsharqNews.m3u8
      run: |
        touch ./sa_AsharqNews.m3u8
        sudo cat >./sa_AsharqNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@AsharqNews/live)
        EOL

    - name: Get sa_AsharqBusiness.m3u8
      run: |
        touch ./sa_AsharqBusiness.m3u8
        sudo cat >./sa_AsharqBusiness.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@AsharqBusiness/live)
        EOL

    - name: Get sa_Alekhbariya.m3u8
      run: |
        touch ./sa_Alekhbariya.m3u8
        sudo cat >./sa_Alekhbariya.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@SaudiNewsTV/live)
        EOL

    - name: Get ye_BelqeesTV.m3u8
      run: |
        touch ./ye_BelqeesTV.m3u8
        sudo cat >./ye_BelqeesTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@BelqeesTV/live)
        EOL

    - name: Get eg_alkaherawalnas.m3u8
      run: |
        touch ./eg_alkaherawalnas.m3u8
        sudo cat >./eg_alkaherawalnas.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/alkaherawalnas/live)
        EOL

    - name: Get eg_AlghadExtra.m3u8
      run: |
        touch ./eg_AlghadExtra.m3u8
        sudo cat >./eg_AlghadExtra.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@AlghadExtra/live)
        EOL

    - name: Get iq_KarbalaTV.m3u8
      run: |
        touch ./iq_KarbalaTV.m3u8
        sudo cat >./iq_KarbalaTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@KarbalatvGroup/live)
        EOL

    - name: Get ke_CitizenTV.m3u8
      run: |
        touch ./ke_CitizenTV.m3u8
        sudo cat >./ke_CitizenTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/Kenyacitizentv/live)
        EOL

    - name: Get ke_KTNNewsKenya.m3u8
      run: |
        touch ./ke_KTNNewsKenya.m3u8
        sudo cat >./ke_KTNNewsKenya.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/user/standardgroupkenya/live)
        EOL

    - name: Get mx_adn40Mx.m3u8
      run: |
        touch ./mx_adn40Mx.m3u8
        sudo cat >./mx_adn40Mx.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@ADN40MX/live)
        EOL

    - name: Get mx_TelevisaPuebla.m3u8
      run: |
        touch ./mx_TelevisaPuebla.m3u8
        sudo cat >./mx_TelevisaPuebla.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=104857600
        $(yt-dlp -g https://www.youtube.com/@televisapuebla/live)
        EOL

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: y8 m3u8
        path: .

    - name: Git push assets to "y8" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b y8
        git add .
        git commit -m "Update y8"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin y8
